language: node_js
sudo: false
node_js:
- 7
- 6
- 4
env:
  global:
  - secure: XTZLVsSkM70v7qpJOl2PcNbxqN05ous7jpsCp8AqxrAPEuCZK9acCoXbm1Nvo0uAor3NAuiqEgzSpgGZwvsxLTGpVopUVSyFTynqIrn6heSNqJzAYWOdvlS/3oFmOGoRLabDojmaDk6forbXS9F8w9gVm9Auf1YC/wzQaawe1hVnRBlaLa+h6QofjHUb14rUVst/NYB/lDq+XAt6zzo9JGPRJXCwaNCR8DZxCt2d/Xe9o+CJ7u4Fwg6ES1ExVwATazSEQWe+fQYz7ny7xHn9FXWykk6m7h0p1DsUpTBnPRYcG21VdXpS5PatAK2qStKxd2WAootkkxjjwPNjXyrlxWbI3NgnH7WfOvUCca7LLgkgRB+BD2D+28OIgjPHQ2xzBDrZ7ADniPi9anu3clHAIq5swc8aAeEGSptzQQzHJ1BfSqb55bLAdroVdzO7Pl4X5zomuaPzgZRhhhOtCAhg4AzqqRlOw0kcp1qC03wZrTYwIQkEEOFPKPWXgs37OzqOtX0Rua2DvJYsX8EKTAhi7wfXFWymRAY2uGrRVLyAxdC9UA/WbKM8QwA63pKUUvLXt/NdecMGyzQxM5bRiKdbElbQOn5oMZMqfRzxM5OC9sajqojGFBMKdw9osQ8EtfUfAYxGMtfYZk94Ljfmcg/GrL9WIVdJMU8JMpEMEPgr8Wo=
  - secure: Z1QJPbc27RFJC7noId9iHv1Ybp/EWDSmfG3AF2xDtqURxRvhvIyUvi+lf/IS38vlVRZgPWRUc5FQqfxlQ1Zwy7l5QyWdVg61scYkRv0Z8I/ktzw95AAfw2KgTonqZFRWiNbpmbw/BiDzocx445jNHYQ1QzhLqFX8HaNIWTinVWeZlWRjMnOE7qvY3O013mG9urspEdfiRh2XpJ5vzUkTYufFNttrK7B8K1hKGFd89VkBCJhwMyYcqFWKGOgiV4Fp/7A5gC+M/RGwZv3lJpGgsmTFFhhpqwZFr6YyaUE89BrEarAbZk6KDXLIuD+GqTp5eZO9ifXI1GZ5HggKx5wJOMoXKoxiU+WTo53gwVE/sXdONOl0D2KMv+ICAUuWIgCGx5Qy/x5iGAKPKkc160MTzYs5upXrPZxeVNPAxpnY1Pi8vm9m6ei9gR0APxPomrv84jLigqy6iFiaTsH8/Uu7DMAYoXdJkBXgPSPd3TvzPbBTMjZAjNnmqJtByjmfHG6QxMZ+Usx2XO9KtHQV+N8S+jZm3K140eKf0czCeJv2cyJKLxpUlDjyuolx8iioSXZ2BAWW+M18Nuh8mhbw0VT/gDel7RDrloLIKsheYmcLgSDFOIfzE//SuUQ5y8jdkYwCQYzccVFfkyitcMxO12ICOVe5vuqTgBzegIyQK8+1X3Q=
  - K2_BUCKET: ops.tonym.us
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: npm
  on:
    tags: true
  api_key:
    secure: SkOWWOL4HFmahUmku/q9862Jm7lFPmHFaMexok7xvCAoJDYmBbEzUoTzgkA6gG6YW42LqFrU+goV0SePKhm9EeIkAESmukB9wYOt3bGr1DJURiL21DxpvaBN+BiYNbvsKQcLf96LMVrFmSsxxkKGpmPaT755MUD1e5rAH3Upr3dLUMuKTc6u9GMDrmWbB2VZe6IB92DY9W5qL2wHkr6arLddWiSv2ciEOK9lMwGCO+MtgyNmT8Iy/fLVSObECkTm3E6dxw2pleJv+fCA24etu8j3a+EkLk5BuXYwbkDDHLpVVJAP0m0aMq1X1wfu05bNSQESkXW3CZfb32SHK23Anjmj3SNI09q7fDuIWZ3kogEm5SU+HrvG5SrobWiTFIhFYqE0+z15ipjebZykDDqvEBo9ypTMzAU/oZbn+UOLbpBW0zT3D46xotdxd7zEwUZ7u06jwQwkt2AAP+Ot0v0PiwYimd2Bht01EntPSQqyprJ3I60NE04fK2ttCj0pQd6bK4oaMW7hdf0ZpFd/+GeGKfS38wVkNWjbhx8dd5eRkLUb2w51igeTKBYwI8d4yh491cifroHcozeZDb/vQBSJMyBtjYZJ9b1SvTMEy3B9EgaVU5pcpLnm/bPHn8Kt0ra/SPdSj0eTM6iyhoZhlA2glHbnCAkk8+4RcvO1RDrtCso=
