language: node_js
sudo: false
node_js:
- 7
- 6
- 4
env:
  global:
  - K2_BUCKET: ops.tonym.us
  - secure: Ur+BgV5Gj8zRayBvc1FqYsVc/gLJb44yuu0AiCtKRBoXvyY6OXUKAtnAbHdvGl6ST1F+6Oxf7UfLoBiQDnQWVBmxlK2jMu5v50lXPB+oZkfUdw3Le43DQOWDez336Y0XK1nU5l5fdkJAxuNfkYaZcxIUfnH8SjQB/EeCO0TCb9Nmd3yJNZfULVtUMppKR1TmDPaqSJ8ySigmsSZRPoLFW8O3A0UUrgcGE313py2g7Qxq+03I9MXASCjLmQXodqUNHBd5e+wGi4ZbBfkGUpsPXTYcimpn1SwAJ4dzq56DYshUOp1Q/GKFvef4QPac2FZIdK/uwrTB7nSm9HZ0r8X/0LNYrdLJCTUdhHPB9gx+7Lz6pkPy7LJVHzhHmRx/UG6iRpem0lL8QZVaQegIv2SktSlB/vc+91papPZ+7BdZNoiST6z+TNn2E8E57JiOVvZaWfg2u8TP03GfcnwHFy2rn0z1auEbF/xsVBM7f0GM/ZPTffdrLY/MqD6ZYlIXmWtA58JSVXZ3t9HyM1CN7yr7pJnEJR/mzxYsS5TXHGuYkuR8JEP6mx3feXpNr0LSmzpDXiZshEaN4dMDPNnWB6p1iIMNUvD+QunAFdviW/pKBLRoqn4AwWWjhQ8+Vi+iAEyJFNw0WfTQy9glHWvzbVF6QRY3IcW+UhMI4m1LRzouOJs=
  - secure: ce5iWupH7FOqhBTyXYn0pXkxxVYa+kJ8+Ia6T8CYthcrTHX/b5IveeOuj/xRn2OIazYXQ4rkj+0NOxY5KtWHuxIDRItF6BTgtTI/P0Ssmt+j7tNW9tITsZHI7blTyi7gM0xtGY9XZ5tfcseiiInUI37nzv4iYKhFWBi+5UzWzJAfL9FVg0ssPsb6h+pwnnDS+edghuBSYH5PDCHlJgPtwcOcs2wjgwwCHfeHEdRP68J7OgWuYnez+3RHI/piw99sdVEScx2HuHQpUl6LMXTy6RIhTTTAKMP30d62NHg2NlzhZkMIr4WigkrTZmxAAl/FWa1XusB/hwtMNsP7OzJVp6iKt2+MsGvbCSo47ANdo6CReB6lGYxF+YAcflc2XyIg+bhS0x1yUBcNUkEOGKkhJDjb3m7kq7wAeEweiKG2DGcdPOmwq/2hkAUDBSvJCMWZM+BVlBsZkT9e7bGbA6b7aaZ+3n5Fznbh9JhbBTj8Ivkl0JHBZttbGyex37Lnro9KTHntQAFna1/7L+cEBmiB2+4F3zHDJHD4wDMIt6CjH/2hDP6FzTp6XXcaEbOO/vWhLEYGS63RF5Zmw1oNgEDpKRWSJvBKoXk3uZ66bWZzoKHTxBQBKiM4VIJ4DoMHhUTs/796ZRa92L56YD6yAniFmOPZV+4RBKkXcz4ecMAKJD0=
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  email: tonym@tonym.us
  provider: npm
  on:
    tags: true
  api_key:
    secure: SkOWWOL4HFmahUmku/q9862Jm7lFPmHFaMexok7xvCAoJDYmBbEzUoTzgkA6gG6YW42LqFrU+goV0SePKhm9EeIkAESmukB9wYOt3bGr1DJURiL21DxpvaBN+BiYNbvsKQcLf96LMVrFmSsxxkKGpmPaT755MUD1e5rAH3Upr3dLUMuKTc6u9GMDrmWbB2VZe6IB92DY9W5qL2wHkr6arLddWiSv2ciEOK9lMwGCO+MtgyNmT8Iy/fLVSObECkTm3E6dxw2pleJv+fCA24etu8j3a+EkLk5BuXYwbkDDHLpVVJAP0m0aMq1X1wfu05bNSQESkXW3CZfb32SHK23Anjmj3SNI09q7fDuIWZ3kogEm5SU+HrvG5SrobWiTFIhFYqE0+z15ipjebZykDDqvEBo9ypTMzAU/oZbn+UOLbpBW0zT3D46xotdxd7zEwUZ7u06jwQwkt2AAP+Ot0v0PiwYimd2Bht01EntPSQqyprJ3I60NE04fK2ttCj0pQd6bK4oaMW7hdf0ZpFd/+GeGKfS38wVkNWjbhx8dd5eRkLUb2w51igeTKBYwI8d4yh491cifroHcozeZDb/vQBSJMyBtjYZJ9b1SvTMEy3B9EgaVU5pcpLnm/bPHn8Kt0ra/SPdSj0eTM6iyhoZhlA2glHbnCAkk8+4RcvO1RDrtCso=
