language: node_js
sudo: false
node_js:
- stable
- 6
- 4
env:
  global:
  - K2_BUCKET: ops.tonym.us
  - secure: Ur+BgV5Gj8zRayBvc1FqYsVc/gLJb44yuu0AiCtKRBoXvyY6OXUKAtnAbHdvGl6ST1F+6Oxf7UfLoBiQDnQWVBmxlK2jMu5v50lXPB+oZkfUdw3Le43DQOWDez336Y0XK1nU5l5fdkJAxuNfkYaZcxIUfnH8SjQB/EeCO0TCb9Nmd3yJNZfULVtUMppKR1TmDPaqSJ8ySigmsSZRPoLFW8O3A0UUrgcGE313py2g7Qxq+03I9MXASCjLmQXodqUNHBd5e+wGi4ZbBfkGUpsPXTYcimpn1SwAJ4dzq56DYshUOp1Q/GKFvef4QPac2FZIdK/uwrTB7nSm9HZ0r8X/0LNYrdLJCTUdhHPB9gx+7Lz6pkPy7LJVHzhHmRx/UG6iRpem0lL8QZVaQegIv2SktSlB/vc+91papPZ+7BdZNoiST6z+TNn2E8E57JiOVvZaWfg2u8TP03GfcnwHFy2rn0z1auEbF/xsVBM7f0GM/ZPTffdrLY/MqD6ZYlIXmWtA58JSVXZ3t9HyM1CN7yr7pJnEJR/mzxYsS5TXHGuYkuR8JEP6mx3feXpNr0LSmzpDXiZshEaN4dMDPNnWB6p1iIMNUvD+QunAFdviW/pKBLRoqn4AwWWjhQ8+Vi+iAEyJFNw0WfTQy9glHWvzbVF6QRY3IcW+UhMI4m1LRzouOJs=
  - secure: ce5iWupH7FOqhBTyXYn0pXkxxVYa+kJ8+Ia6T8CYthcrTHX/b5IveeOuj/xRn2OIazYXQ4rkj+0NOxY5KtWHuxIDRItF6BTgtTI/P0Ssmt+j7tNW9tITsZHI7blTyi7gM0xtGY9XZ5tfcseiiInUI37nzv4iYKhFWBi+5UzWzJAfL9FVg0ssPsb6h+pwnnDS+edghuBSYH5PDCHlJgPtwcOcs2wjgwwCHfeHEdRP68J7OgWuYnez+3RHI/piw99sdVEScx2HuHQpUl6LMXTy6RIhTTTAKMP30d62NHg2NlzhZkMIr4WigkrTZmxAAl/FWa1XusB/hwtMNsP7OzJVp6iKt2+MsGvbCSo47ANdo6CReB6lGYxF+YAcflc2XyIg+bhS0x1yUBcNUkEOGKkhJDjb3m7kq7wAeEweiKG2DGcdPOmwq/2hkAUDBSvJCMWZM+BVlBsZkT9e7bGbA6b7aaZ+3n5Fznbh9JhbBTj8Ivkl0JHBZttbGyex37Lnro9KTHntQAFna1/7L+cEBmiB2+4F3zHDJHD4wDMIt6CjH/2hDP6FzTp6XXcaEbOO/vWhLEYGS63RF5Zmw1oNgEDpKRWSJvBKoXk3uZ66bWZzoKHTxBQBKiM4VIJ4DoMHhUTs/796ZRa92L56YD6yAniFmOPZV+4RBKkXcz4ecMAKJD0=
  - secure: UAfiDlD6RF6d3dDH3Nf8ZYDKQFzzToUhP8ymqxILgyvYjXwjB3Kigi8Wh5T8ln3p9zxQFt4oCIDnekN5NUSGCNAnMaobC9SFSA6bsCwCtAviuH3DA8/mFSOmmC0P4+9H73BaYxDTPA9/FYE2z4T4NAjEUo9VwhCZqnns82IfV8ZPc2nN9iyNHVqZ2+YOGPu9NnxswBZOejITLqYJh00jXXl87mH7POcbnj6RWZs16ki/Fy7ZFC9g+ga8Wyc6J0oQfBqlEv0aXXmCgAgEIONhstPWyv/6ndGI46+GRmbvBYU39Kwk15WxO6GoIm2ZwRKfl5Oomc0YY/o4sOHKedJC2RlZYRir9g3+ZPJh6wkIGvSUgsaRi1ikCZcoapm3XM+fUIBTrn6CiXJimigBHhzwugHzXp1fAi5K63DUf+iTjWh0wHCDmaUX2r15bp0aARZ2hw76DlKfh3jzZZbXcvxes9Jn59lLZSsDmCDaBGadGc+CbRmBZS3n7jmBCnuFZBl+zIKWmJynIEz1lBj4TCKqWkfJ96w6C7lY3A4rJtlNgy78DJwNB0Bi2fLwVbSLTolN2wmfYuL8g8NwusvEXc3kG7vrkj7kO49Ui15XqHkRuwqCc8X0OFVp/XXrN/uFU50I2lVVjG8xDIg972dRIh0jJKr2oRsMv+r/3Xw8emCzNP0=
  - secure: dD5aIwZpSsFn4efP5i3RVeGbj49pRYPUyiHg3t5XqqbBHyBRaw7hZfaU0qw0wQmxFTfaQMWMt6u+5QjSaqIwUeAE0kLK2OjVEVPZRGra8x0BxPcv8XsOZ6QJxZ/Ndi0BU4LTb/cXfgiweI4UNX4drz9LHmfIICnFDHF4GcqcRdBUKoiCio2CLcLRyLl8MRbL0Qmb6Sn7lfDVbDtOZGP0QVSdLtSX7KWnz2UL0jF9mDAdP35ANdQawIwadM/kkoIUr47/KU4fmbH68dOhIY2z/AZnRGzvNQWndax/LDyusJSuJgC3hqYVEluzHQ2l88UNjDu0bY7rGdx5VBsq5aygifC5MLw7C5pJ1ZK4oPQPr02vjDeGpy0xm/Kcu5O1xnL+eCgF1d37CY2PPqH6TMyK5em5QNnkB4dMwVvb0IediNfObBdESxGvZmlvnYt1DqbdXbr9i8oLQTLUX6zgG+qn28cdfmtgjNxsJdjJka1lByQVlWaB8d0PABNCNJLA3gTO7E2KuPSIOufowW8Xyn3nOYvlBbpQhdKPztkpMBVqnByAFEvARJxvNmrdOrM2eqTGyW1cRUudO62FAYcv6yTHeMKjVxsCaq+Q5xQIeSzGBCx1AEYOn2oMcET/XGGOuMqsDMp2ksEHaCkd7v0WXoXeRYfUu9c8J+qPCvqqBaTY13Q=
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn --ignore-engines
script:
- yarn lint
- yarn test
jobs:
  include:
  - stage: npm release
    node_js: stable
    deploy:
      email: tonym@tonym.us
      provider: npm
      on:
        tags: true
      api_key:
        secure: Y2PMcSXiK49bnpBNMcOkjc12Pbjb7QzNnCaYOINr76FlSiXK0J6XV6SjQvuYDs7yNAEc0YoS6YtgEvrd/a7zZoYX32VR1BihFh53BDQChZ8u3qDpg0O4klahHjBx6vtEoonqUwAhoVRo963R5ZLhsrFZZoTIq5OjZn0/e2GSGWQSrpgnlqRkUjVZdXryCSwNzbsk7eE/CpzteWJDL3NO0mp7Wr3evQMz2py6lHSrpr+cexo7p5E5M7D2hzg7aPyKXajS/biZOmMvi0nyzgOG8mSZEi2WcN5IB0n7DDlkn+sq8FiVLqxbvn1YqXNiQeN3iA3Y8t8qLZspX/i/SBvqaUMTyVkzwwOb0ztMu21cK5owTaFYuM1WMPihuhsdoAUtl59JvOwzc+DTXMUtsgjUIzMke9LX4qMgHL9c7Hl0504OxlfwVPVOTjl8hfOw960l1MJX1hHedrjbNGXqqtu+/O1B3wmjZBBvVIHb+jO45ihTbWd4OX5NFG52rZv95M1Wv79sAihj11brebSKHgEYq7sjhJEunTF9XDjGk000TZrO4zlB1s6ltRyBOco4kh0Ftm+BVgNFC6qdMd0FkacYv9hm6TUtF7sEVlMuhEXZNeuHxbCuqAIAtZbppA2Ffwchc1Crzp6eNl+M+Kywy9NsxCLSUtKzsusqj//rcBmbSUw=
